export const metadata = {
  title: 'CortexFlow - Open-source Container Networking Infrastructure and Monitoring Platform',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
