name: cortexflow server build

on: 
  push:
    branches:
      - master  

jobs:
  build:
    name: site builder
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository  
        uses: actions/checkout@v3  

      - name: Install dependencies  
        run: npm install --force            

      - name: Build the site        
        run: npm run build         

      - name: List build directory
        run: ls -l 