name: cortexflow server deployment

on: 
  push:
    branches:
      - master  

jobs:
  build:
    name: site builder
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository  
        uses: actions/checkout@v3  

      - name: Install dependencies  
        run: npm install --force            

      - name: Build the site        
        run: npm run build         

  deploy:
    name: site deploy via FTP
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository  
        uses: actions/checkout@v2

      - name: Deploy via FTP       
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_HOST }}      
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: build                
          remoteDir: /www.cortexflow.org    
