name: cortexflow server deployment

on: 
  push:
    branches:
      - master  

jobs:
  build:
    name: site builder
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository  
        uses: actions/checkout@v3  

      - name: Install dependencies  
        run: npm install --force            

      - name: Build the site        
        run: |
          npm run build
          # Check if build directory was created
          if [ ! -d build ]; then
            echo "Build directory was not created. Exiting..."
            exit 1
          fi

      - name: List build directory after build
        run: |
          echo "Current Directory: $PWD"
          echo "Listing files in the build directory:"
          ls -l build # List files and directories in the build folder

  deploy:
    name: site deploy via FTP
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout repository  
        uses: actions/checkout@v3  # Use the same version of checkout

      - name: List current directory before deploy
        run: |
          echo "Current Directory: $PWD"
          ls -l  # List files in the current directory before deployment

      - name: Check if build directory exists
        run: |
          if [ -d build ]; then
            echo "Build directory exists."
          else
            echo "Build directory does NOT exist!"
            exit 1
          fi

      - name: List contents of build directory before deploy
        run: |
          echo "Contents of build directory:"
          ls -l build # List files in the build folder before deployment

      - name: Deploy via FTP       
        uses: sebastianpopp/ftp-action@releases/v2
        with:
          host: ${{ secrets.FTP_HOST }}      
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          localDir: build/*  # Use wildcard to upload only the contents of the build directory
          remoteDir: /www.cortexflow.org     # Remote directory where files will be uploaded
