name: Update documentation

on: 
  push:
    branches: [master]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Nodejs
        uses: actions/setup-node@v3
        with:
          node-version: '20.15.0'


      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build

      - name: Deploy to site host
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.FTP_SERVER }}
          user: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local_dir: './build'
          remote_dir: ${{ secrets.CF_SITE_DIR }}